
  // This file was autogenerated by dynamically running setEnv.ts and using dotenv for managing API key secrecy
  export const environment = {
    production: false,
    OPENAI_API_KEY: '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'
  };
